### ISSUE TITLE
 longer lasting ghost hitboxes

### ISSUE THREAD

**Issue by Zedb0T** [JoKronk/teamruns-jak-project#41]

**Comment by The-Stellar** [comment]
This is a thing in 1.6, but it's just much worse in the rebased version

**Comment by The-Stellar** [comment]
This behaviour is very consistent around the first cell in Geyser, it almost looks like the hitbox freezes when it crosses a certain radius from the cell, both ingoing and outgoing
https://github.com/user-attachments/assets/6ed9134f-77a8-423c-961a-c7331f537a52

**Comment by The-Stellar** [comment]
Similarly, with this cell you can see that the hitbox continues, presumably with whatever momentum the target had, during the cutscene when the target is stationary

Uploading ghost hitboxes 2.mp4…

**Comment by The-Stellar** [comment]
I think the behaviour shown in the second video is due to the velocity of remote targets not being set to 0 during the cutscene?
It then keeps stepping the collision every frame by the same amount until the cutscene ends.
